collections:
- name: ansible.posix
  version: ">=1.4"
- name: community.crypto
  version: ">=2.15"
- name: community.general
  version: ">=7.4"

roles:
- name: shinesolutions_opensource.vars_schema_validator
  src: git+https://github.com/shinesolutions/ansible-role-vars-schema-validator
  version: "master"
